"use client";

import { motion } from "framer-motion";
import { FileText, Download, Check, ShieldCheck } from "lucide-react";
import { useAuthStore } from "@/store/auth-store";
import { useAuditStore } from "@/store/audit-store";
import { staggerContainer, fadeInUp } from "@/lib/motion";

const REGS = [
  "EU AI Act (Risk Category: Low)",
  "GDPR (Art. 22 Compliance)",
  "ECOA (Fair Lending Audit)",
];

const TOC = [
  { title: "Executive Summary", page: "Pg. 1" },
  { title: "Algorithmic Bias Assessment", page: "Pg. 3" },
  { title: "Hallucination Index & Verification", page: "Pg. 5" },
  { title: "Regulatory Alignment Matrix", page: "Pg. 7" },
];

export default function CompliancePage() {
  const { user } = useAuthStore();
  const { reevalResult, auditResult, applicationData } = useAuditStore();
  const caseId = reevalResult?.case_id ?? "PASSPORT-994-SHARMA";
  const subject = applicationData?.name ?? "Aarav Sharma";
  const verdict = reevalResult?.new_decision ?? "APPROVED";

  const handleDownload = () => {
    const content = `VERIFIAI AI ACCOUNTABILITY COMPLIANCE PASSPORT\n\nCASE ID: ${caseId}\nSUBJECT: ${subject}\nDATE: ${new Date().toISOString().slice(0, 10)}\nGENERATED BY: ${user?.name} · ${user?.organization}\n\nVERDICT: ${verdict}\nCONFIDENCE: ${reevalResult?.confidence ? Math.round(reevalResult.confidence * 100) : 94}%\n\nTABLE OF CONTENTS:\n${TOC.map(t => `${t.title} — ${t.page}`).join("\n")}\n\nREGULATORY COVERAGE:\n${REGS.join("\n")}\n\nFILE SIZE: 2.4 MB | LENGTH: 8 Pages | ENCRYPTION: AES-256\n\n— VerifAI v2.0`;
    const a = document.createElement("a");
    a.href = "data:text/plain," + encodeURIComponent(content);
    a.download = `${caseId}.txt`;
    a.click();
  };

  return (
    <div style={{ maxWidth: 980, margin: "0 auto" }}>
      <motion.div variants={staggerContainer} initial="hidden" animate="visible">
        <motion.div variants={fadeInUp} style={{ marginBottom: 4 }}>
          <p className="mono-label" style={{ marginBottom: 4 }}>CASE ID: {caseId}</p>
          <h1 style={{ fontFamily: "var(--font-serif)", fontSize: 36, fontWeight: 900, color: "var(--text-primary)", marginBottom: 24 }}>Compliance Passport</h1>
        </motion.div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 280px", gap: 20 }}>
          {/* Document preview */}
          <motion.div variants={fadeInUp} className="card" style={{ padding: 32 }}>
            {/* Header */}
            <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 24, paddingBottom: 20, borderBottom: "1px solid var(--bg-border)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <ShieldCheck size={18} style={{ color: "var(--accent)" }} aria-hidden="true" />
                <div>
                  <p style={{ fontFamily: "var(--font-mono)", fontWeight: 700, fontSize: 13, color: "var(--text-primary)" }}>VERIFIAI</p>
                  <p style={{ fontFamily: "var(--font-mono)", fontSize: 9, color: "var(--text-tertiary)" }}>AI ACCOUNTABILITY COMPLIANCE PASSPORT</p>
                </div>
              </div>
              <div style={{ textAlign: "right", fontFamily: "var(--font-mono)", fontSize: 10 }}>
                <p style={{ color: "var(--text-tertiary)" }}>DATE: {new Date().toISOString().slice(0, 10)}</p>
                <p style={{ color: "var(--text-tertiary)" }}>TIME: {new Date().toISOString().slice(11, 19)} UTC</p>
              </div>
            </div>

            <h2 style={{ fontFamily: "var(--font-serif)", fontSize: 26, fontWeight: 900, color: "var(--text-primary)", marginBottom: 6 }}>
              Subject: {subject}
            </h2>
            <p style={{ fontSize: 13, color: "var(--text-secondary)", marginBottom: 24, lineHeight: 1.6 }}>
              Comprehensive audit trail and regulatory compliance verification for automated decisions rendered regarding the subject.
            </p>

            {/* Verdict badge */}
            <div style={{ display: "inline-flex", alignItems: "center", gap: 10, padding: "10px 16px", borderRadius: 8, border: "1px solid var(--accent-border)", background: "var(--accent-glow)", marginBottom: 28 }}>
              <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--text-secondary)", fontWeight: 700, letterSpacing: "0.06em" }}>VERDICT</span>
              <span style={{ fontFamily: "var(--font-mono)", fontSize: 14, fontWeight: 700, color: "var(--verified)" }}>{verdict}</span>
              <span style={{ fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--text-tertiary)" }}>CONFIDENCE: {reevalResult?.confidence ? Math.round(reevalResult.confidence * 100) : 94}%</span>
            </div>

            {/* TOC */}
            <div>
              <p className="mono-label" style={{ marginBottom: 12 }}>Table of Contents</p>
              {TOC.map((t, i) => (
                <div key={i} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 0", borderBottom: "1px solid var(--bg-border)" }}>
                  <span style={{ fontSize: 13, color: "var(--text-primary)" }}>{i + 1}. {t.title}</span>
                  <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--text-tertiary)" }}>{t.page}</span>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Sidebar */}
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            {/* Metadata */}
            <motion.div variants={fadeInUp} className="card" style={{ padding: 20 }}>
              <h3 style={{ fontFamily: "var(--font-sans)", fontSize: 14, fontWeight: 700, color: "var(--text-primary)", marginBottom: 14 }}>Document Metadata</h3>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                {[
                  { l: "FILE SIZE", v: "2.4 MB" },
                  { l: "LENGTH", v: "8 Pages" },
                  { l: "FORMAT", v: "PDF/A-3" },
                  { l: "ENCRYPTION", v: "AES-256" },
                ].map((m) => (
                  <div key={m.l}>
                    <p className="mono-label" style={{ marginBottom: 2 }}>{m.l}</p>
                    <p style={{ fontFamily: "var(--font-mono)", fontSize: 13, fontWeight: 700, color: "var(--text-primary)" }}>{m.v}</p>
                  </div>
                ))}
              </div>
            </motion.div>

            {/* Regulatory */}
            <motion.div variants={fadeInUp} className="card" style={{ padding: 20 }}>
              <h3 style={{ fontFamily: "var(--font-sans)", fontSize: 14, fontWeight: 700, color: "var(--text-primary)", marginBottom: 12 }}>Regulatory Coverage</h3>
              {REGS.map((r) => (
                <div key={r} style={{ display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 10 }}>
                  <Check size={13} style={{ color: "var(--verified)", flexShrink: 0, marginTop: 1 }} aria-hidden="true" />
                  <span style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.4 }}>{r}</span>
                </div>
              ))}
            </motion.div>

            {/* Download */}
            <motion.button variants={fadeInUp} onClick={handleDownload} whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.97 }}
              className="btn-primary" style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, padding: "13px" }}>
              <Download size={16} aria-hidden="true" /> Generate &amp; Download PDF
            </motion.button>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
